version: "3"
services:
  web:
    image: tbhavik1/reactapp_web
    ports:
      - 80:80
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
        failure_action: rollback
