FROM node:alpine as nodework

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

ENV VITE_APP_NAME=dockerApp

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
# CMD ["npm", "run", "dev"]
